# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = "dotfiles"

[settings]
# An array of toml files paths containing the variables to inject in your templatized dotfiles
# You can have multiple var files as long as variable names does not colide.
# vars = [ "vars.toml" ]

# An array of post install shell commands
# posthooks = [ "sway reload" ]

[settings.dots]
# A dot entry representing a symlink, `source` is relative to `dotfiles_dir`
# and `target` shall be relative to $HOME directory or absolute.

vim = { source = "vim/.vimrc", target = ".vimrc" }
vimDir = { source = "vim", target = ".vim" }
neovim = { source = "nvim", target = ".config/nvim" }
tmuxDir = { source = "tmux", target = ".tmux" }
tmux = { source = "tmux/tmux.conf", target = ".tmux.conf" }
zsh = { source = "zsh/zshrc", target = ".zshrc" }
ohmyzsh = { source = "zsh/oh-my-zsh", target = ".oh-my-zsh" }
alacritty = { source = "alacritty", target = ".config/alacritty" }
gitConfig = { source = "gitconfigs/gitconfig", target = ".gitconfig" }
gitIgnore = { source = "gitconfigs/gitignore", target = ".gitignore" }
gitTemplate = { source = "gitconfigs/git_template", target = ".git_template" }

[profiles.hypr]
# hypr specific settings
[profiles.hypr.dots]
hyprland = { source = "hyprland", target = ".config/hypr" }
