#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar
# If all your bars have ipc enabled, you can also use
# polybar-msg cmd quit

# Launch
#echo "---" | tee -a /tmp/polybar1.log
#polybar main --config=$HOME/.config/i3/polybar/config 2>&1 | tee -a /tmp/polybar1.log & disown
#
#echo "Bars launched..."
#

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload main --config=$HOME/.config/i3/polybar/config &
  done
else
  polybar --reload example &
fi
