import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 6

[font.glyph_offset]
x = 0
y = 3

[shell]
args = ["--login"]
program = "/bin/zsh"

[window.padding]
x = 15
y = 15

